### ISSUE TITLE
WebSerial code

### ISSUE THREAD

**Issue by SeriousM** [williamkapke/webserial#2]
Hi @williamkapke,

thank you so much for creating this service! It helped me very much discovering my serial device.
May I ask if I can use your webserial code from `connection.js` in my little project?
You didn't put any license information into the repository so I guess it's a gentleman move to ask for permission.

Thank you!

**Comment by williamkapke** [comment]
At the bottom of the page, I assigned it [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)

... but def slacked on adding it the standard ways to the code (package.json, LICENSE file, README)

Thanks for asking first! Much appreciated.
